server.port=8080

# Ukuran upload Excel (parsing asli akan dibaca di server)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB

# Log engine agar mudah diamati
logging.level.com.iconplus.sld=INFO